version: '2'

services:
  aspnetcore_mvc_docker:
    image: username/aspnetcore_mvc_docker:Debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "24954:80"
    volumes:
      - .:/app
