version: '2'

services:
  aspnetcore_hello_world_docker:
    image: username/aspnetcore_hello_world_docker:Debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "28612:80"
    volumes:
      - .:/app
